"""
Canonical country identity module.

Single source of truth for:
  1. Country display names (ISO-3 -> clean, consistent English name)
  2. Continent/region assignments (ISO-3 -> region code)
"""

from __future__ import annotations

REGION_NAMES: dict[str, str] = {
    "AF": "Africa",
    "AS": "Asia",
    "EU": "Europe",
    "NA": "North America",
    "SA": "South America",
    "OC": "Oceania",
}

COUNTRY_REGIONS: dict[str, str] = {
    "ABW": "NA",
    "AFG": "AS",
    "AGO": "AF",
    "AIA": "NA",
    "ALB": "EU",
    "AND": "EU",
    "ARE": "AS",
    "ARG": "SA",
    "ARM": "AS",
    "ASM": "OC",
    "ATG": "NA",
    "AUS": "OC",
    "AUT": "EU",
    "AZE": "AS",
    "BDI": "AF",
    "BEL": "EU",
    "BEN": "AF",
    "BES": "NA",
    "BFA": "AF",
    "BGD": "AS",
    "BGR": "EU",
    "BHR": "AS",
    "BHS": "NA",
    "BIH": "EU",
    "BLM": "NA",
    "BLR": "EU",
    "BLZ": "NA",
    "BMU": "NA",
    "BOL": "SA",
    "BRA": "SA",
    "BRB": "NA",
    "BRN": "AS",
    "BTN": "AS",
    "BWA": "AF",
    "CAF": "AF",
    "CAN": "NA",
    "CHE": "EU",
    "CHL": "SA",
    "CHN": "AS",
    "CIV": "AF",
    "CMR": "AF",
    "COD": "AF",
    "COG": "AF",
    "COK": "OC",
    "COL": "SA",
    "COM": "AF",
    "CPV": "AF",
    "CRI": "NA",
    "CUB": "NA",
    "CUW": "NA",
    "CYM": "NA",
    "CYP": "AS",
    "CZE": "EU",
    "DEU": "EU",
    "DJI": "AF",
    "DMA": "NA",
    "DNK": "EU",
    "DOM": "NA",
    "DZA": "AF",
    "ECU": "SA",
    "EGY": "AF",
    "ERI": "AF",
    "ESP": "EU",
    "EST": "EU",
    "ETH": "AF",
    "FIN": "EU",
    "FJI": "OC",
    "FLK": "SA",
    "FRA": "EU",
    "FRO": "EU",
    "FSM": "OC",
    "GAB": "AF",
    "GBR": "EU",
    "GEO": "AS",
    "GGY": "EU",
    "GHA": "AF",
    "GIB": "EU",
    "GIN": "AF",
    "GLP": "NA",
    "GMB": "AF",
    "GNB": "AF",
    "GNQ": "AF",
    "GRC": "EU",
    "GRD": "NA",
    "GRL": "EU",
    "GTM": "NA",
    "GUF": "SA",
    "GUM": "OC",
    "GUY": "SA",
    "HKG": "AS",
    "HND": "NA",
    "HRV": "EU",
    "HTI": "NA",
    "HUN": "EU",
    "IDN": "AS",
    "IMN": "EU",
    "IND": "AS",
    "IRL": "EU",
    "IRN": "AS",
    "IRQ": "AS",
    "ISL": "EU",
    "ISR": "AS",
    "ITA": "EU",
    "JAM": "NA",
    "JEY": "EU",
    "JOR": "AS",
    "JPN": "AS",
    "KAZ": "AS",
    "KEN": "AF",
    "KGZ": "AS",
    "KHM": "AS",
    "KIR": "OC",
    "KNA": "NA",
    "KOR": "AS",
    "KWT": "AS",
    "LAO": "AS",
    "LBN": "AS",
    "LBR": "AF",
    "LBY": "AF",
    "LCA": "NA",
    "LIE": "EU",
    "LKA": "AS",
    "LSO": "AF",
    "LTU": "EU",
    "LUX": "EU",
    "LVA": "EU",
    "MAC": "AS",
    "MAF": "NA",
    "MAR": "AF",
    "MCO": "EU",
    "MDA": "EU",
    "MDG": "AF",
    "MDV": "AS",
    "MEX": "NA",
    "MHL": "OC",
    "MKD": "EU",
    "MLI": "AF",
    "MLT": "EU",
    "MMR": "AS",
    "MNE": "EU",
    "MNG": "AS",
    "MNP": "OC",
    "MOZ": "AF",
    "MRT": "AF",
    "MSR": "NA",
    "MTQ": "NA",
    "MUS": "AF",
    "MWI": "AF",
    "MYS": "AS",
    "MYT": "AF",
    "NAM": "AF",
    "NCL": "OC",
    "NER": "AF",
    "NGA": "AF",
    "NIC": "NA",
    "NIU": "OC",
    "NLD": "EU",
    "NOR": "EU",
    "NPL": "AS",
    "NRU": "OC",
    "NZL": "OC",
    "OMN": "AS",
    "PAK": "AS",
    "PAN": "NA",
    "PER": "SA",
    "PHL": "AS",
    "PLW": "OC",
    "PNG": "OC",
    "POL": "EU",
    "PRI": "NA",
    "PRK": "AS",
    "PRT": "EU",
    "PRY": "SA",
    "PSE": "AS",
    "PYF": "OC",
    "QAT": "AS",
    "REU": "AF",
    "ROU": "EU",
    "RUS": "EU",
    "RWA": "AF",
    "SAU": "AS",
    "SDN": "AF",
    "SEN": "AF",
    "SGP": "AS",
    "SHN": "AF",
    "SLB": "OC",
    "SLE": "AF",
    "SLV": "NA",
    "SMR": "EU",
    "SOM": "AF",
    "SPM": "NA",
    "SRB": "EU",
    "SSD": "AF",
    "STP": "AF",
    "SUR": "SA",
    "SVK": "EU",
    "SVN": "EU",
    "SWE": "EU",
    "SWZ": "AF",
    "SXM": "NA",
    "SYC": "AF",
    "SYR": "AS",
    "TCA": "NA",
    "TCD": "AF",
    "TGO": "AF",
    "THA": "AS",
    "TJK": "AS",
    "TKL": "OC",
    "TKM": "AS",
    "TLS": "AS",
    "TON": "OC",
    "TTO": "NA",
    "TUN": "AF",
    "TUR": "AS",
    "TUV": "OC",
    "TWN": "AS",
    "TZA": "AF",
    "UGA": "AF",
    "UKR": "EU",
    "URY": "SA",
    "USA": "NA",
    "UZB": "AS",
    "VAT": "EU",
    "VCT": "NA",
    "VEN": "SA",
    "VGB": "NA",
    "VIR": "NA",
    "VNM": "AS",
    "VUT": "OC",
    "WLF": "OC",
    "WSM": "OC",
    "YEM": "AS",
    "ZAF": "AF",
    "ZMB": "AF",
    "ZWE": "AF",
}

COUNTRY_NAMES: dict[str, str] = {
    "ABW": "Aruba",
    "AFG": "Afghanistan",
    "AGO": "Angola",
    "AIA": "Anguilla",
    "ALB": "Albania",
    "AND": "Andorra",
    "ARE": "United Arab Emirates",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ASM": "American Samoa",
    "ATG": "Antigua and Barbuda",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",
    "BES": "Bonaire, Sint Eustatius and Saba",
    "BFA": "Burkina Faso",
    "BGD": "Bangladesh",
    "BGR": "Bulgaria",
    "BHR": "Bahrain",
    "BHS": "Bahamas",
    "BIH": "Bosnia and Herzegovina",
    "BLM": "Saint Barthelemy",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BMU": "Bermuda",
    "BOL": "Bolivia",
    "BRA": "Brazil",
    "BRB": "Barbados",
    "BRN": "Brunei",
    "BTN": "Bhutan",
    "BWA": "Botswana",
    "CAF": "Central African Republic",
    "CAN": "Canada",
    "CHE": "Switzerland",
    "CHL": "Chile",
    "CHN": "China",
    "CIV": "Cote d'Ivoire",
    "CMR": "Cameroon",
    "COD": "DR Congo",
    "COG": "Congo",
    "COK": "Cook Islands",
    "COL": "Colombia",
    "COM": "Comoros",
    "CPV": "Cabo Verde",
    "CRI": "Costa Rica",
    "CUB": "Cuba",
    "CUW": "Curacao",
    "CYM": "Cayman Islands",
    "CYP": "Cyprus",
    "CZE": "Czechia",
    "DEU": "Germany",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DNK": "Denmark",
    "DOM": "Dominican Republic",
    "DZA": "Algeria",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ERI": "Eritrea",
    "ESP": "Spain",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FIN": "Finland",
    "FJI": "Fiji",
    "FLK": "Falkland Islands",
    "FRA": "France",
    "FRO": "Faroe Islands",
    "FSM": "Micronesia",
    "GAB": "Gabon",
    "GBR": "United Kingdom",
    "GEO": "Georgia",
    "GGY": "Guernsey",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GIN": "Guinea",
    "GLP": "Guadeloupe",
    "GMB": "Gambia",
    "GNB": "Guinea-Bissau",
    "GNQ": "Equatorial Guinea",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GRL": "Greenland",
    "GTM": "Guatemala",
    "GUF": "French Guiana",
    "GUM": "Guam",
    "GUY": "Guyana",
    "HKG": "Hong Kong",
    "HND": "Honduras",
    "HRV": "Croatia",
    "HTI": "Haiti",
    "HUN": "Hungary",
    "IDN": "Indonesia",
    "IMN": "Isle of Man",
    "IND": "India",
    "IRL": "Ireland",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "ISL": "Iceland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JEY": "Jersey",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KGZ": "Kyrgyzstan",
    "KHM": "Cambodia",
    "KIR": "Kiribati",
    "KNA": "Saint Kitts and Nevis",
    "KOR": "South Korea",
    "KWT": "Kuwait",
    "LAO": "Laos",
    "LBN": "Lebanon",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LCA": "Saint Lucia",
    "LIE": "Liechtenstein",
    "LKA": "Sri Lanka",
    "LSO": "Lesotho",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "LVA": "Latvia",
    "MAC": "Macao",
    "MAF": "Saint Martin",
    "MAR": "Morocco",
    "MCO": "Monaco",
    "MDA": "Moldova",
    "MDG": "Madagascar",
    "MDV": "Maldives",
    "MEX": "Mexico",
    "MHL": "Marshall Islands",
    "MKD": "North Macedonia",
    "MLI": "Mali",
    "MLT": "Malta",
    "MMR": "Myanmar",
    "MNE": "Montenegro",
    "MNG": "Mongolia",
    "MNP": "Northern Mariana Islands",
    "MOZ": "Mozambique",
    "MRT": "Mauritania",
    "MSR": "Montserrat",
    "MTQ": "Martinique",
    "MUS": "Mauritius",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MYT": "Mayotte",
    "NAM": "Namibia",
    "NCL": "New Caledonia",
    "NER": "Niger",
    "NGA": "Nigeria",
    "NIC": "Nicaragua",
    "NIU": "Niue",
    "NLD": "Netherlands",
    "NOR": "Norway",
    "NPL": "Nepal",
    "NRU": "Nauru",
    "NZL": "New Zealand",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PAN": "Panama",
    "PER": "Peru",
    "PHL": "Philippines",
    "PLW": "Palau",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "PRI": "Puerto Rico",
    "PRK": "North Korea",
    "PRT": "Portugal",
    "PRY": "Paraguay",
    "PSE": "Palestine",
    "PYF": "French Polynesia",
    "QAT": "Qatar",
    "REU": "Reunion",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "SAU": "Saudi Arabia",
    "SDN": "Sudan",
    "SEN": "Senegal",
    "SGP": "Singapore",
    "SHN": "Saint Helena",
    "SLB": "Solomon Islands",
    "SLE": "Sierra Leone",
    "SLV": "El Salvador",
    "SMR": "San Marino",
    "SOM": "Somalia",
    "SPM": "Saint Pierre and Miquelon",
    "SRB": "Serbia",
    "SSD": "South Sudan",
    "STP": "Sao Tome and Principe",
    "SUR": "Suriname",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SWE": "Sweden",
    "SWZ": "Eswatini",
    "SXM": "Sint Maarten",
    "SYC": "Seychelles",
    "SYR": "Syria",
    "TCA": "Turks and Caicos Islands",
    "TCD": "Chad",
    "TGO": "Togo",
    "THA": "Thailand",
    "TJK": "Tajikistan",
    "TKL": "Tokelau",
    "TKM": "Turkmenistan",
    "TLS": "Timor-Leste",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TUV": "Tuvalu",
    "TZA": "Tanzania",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "URY": "Uruguay",
    "USA": "United States",
    "UZB": "Uzbekistan",
    "VAT": "Vatican City",
    "VCT": "Saint Vincent and the Grenadines",
    "VEN": "Venezuela",
    "VGB": "British Virgin Islands",
    "VIR": "US Virgin Islands",
    "VNM": "Vietnam",
    "VUT": "Vanuatu",
    "WLF": "Wallis and Futuna",
    "WSM": "Samoa",
    "YEM": "Yemen",
    "ZAF": "South Africa",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}


def get_canonical_name(country_code: str, fallback: str = "") -> str:
    return COUNTRY_NAMES.get(country_code, fallback or country_code)


def get_region(country_code: str, fallback: str = "Unknown") -> str:
    return COUNTRY_REGIONS.get(country_code, fallback)


def get_region_name(region_code: str) -> str:
    return REGION_NAMES.get(region_code, region_code)
